"""Application configuration constants.

Only values that rarely change live here; everything else should remain in env vars.
"""

BUZZHEAVIER_ACCOUNT_ID = "YOOOH7QBFO6DWJPXXDO9"
BUZZHEAVIER_AUTO_UPLOAD_ENABLED = False
BUZZHEAVIER_AUTO_UPLOAD_TIME = 14
BUZZHEAVIER_AUTO_UPLOAD_UNIT = "days"
ENABLE_BUZZHEAVIER = False
ENABLE_STRUCTURED_LOGGING = True


JOB_LOCK_TIMEOUT_SEC = 1800
JOB_TTL_SEC = 86400
LOG_LEVEL = "INFO"
MAX_NEW_UPLOAD = 1
MAX_PD_LOST = 2

PIXELDRAIN_AUTO_UPLOAD_TIME = 115
PIXELDRAIN_AUTO_UPLOAD_UNIT = "days"
REDIS_NO_JOBS_SLEEP_SEC = 15
REDIS_WORKER_INTERVAL_SEC = 5
RETRY_DELAY = 5.0

