STATUS_PENDING = 'pending'
STATUS_COMPLETED = 'completed'
STATUS_FAILED = 'failed'
STATUS_RETRY_PENDING = 'retry_pending'
STATUS_SUCCESS = 'success'
STATUS_ERROR = 'error'
STATUS_RUNNING = 'running'
STATUS_STOPPING = 'stopping'
STATUS_IDLE = 'idle'
STATUS_QUEUED = 'queued'
STATUS_PROCESSING = 'processing'

SERVICE_STATUS_ENABLED = 'enabled'
SERVICE_STATUS_DISABLED = 'disabled'
